version: '2'

services:

  neo4j_1:
    image: my-neo4j
    container_name: neo4j_1
    ports:
      - 7474
      - 7687
      - 7473

  neo4j_2:
    image: my-neo4j
    container_name: neo4j_2
    ports:
      - 7474
      - 7687
      - 7473

  neo4j_3:
    image: my-neo4j
    container_name: neo4j_3
    ports:
      - 7474
      - 7687
      - 7473

  neo4j_extra:
    image: my-neo4j
    ports:
      - 7474
      - 7687
      - 7473